<?php
include "dash_common.php";
?>

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">

                    <div>Register a New IPD Patient
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tab-content">
                    <div class="main-card mb-3 card">
                        <div class="card-body">
                            <h5 class="card-title">Enter The Token Generated By Patient</h5>
                            <form class="" action="functionality/tokenVerifyact.php" method="POST">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="position-relative form-group"><label for="exampleEmail11" class="">Token Number</label><input name="token" placeholder="Token Number Generated By Patient" type="text" class="form-control"></div>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="mb-2 mr-2 btn btn-success btn-lg btn-block" name="submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>